# Generated by Django 2.2.7 on 2019-12-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191202_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles', verbose_name='cover'),
        ),
    ]
