# Generated by Django 2.2.7 on 2019-12-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191204_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=303, null=True, verbose_name='abstract'),
        ),
    ]
