# Generated by Django 2.2.7 on 2019-12-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191216_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='color',
        ),
    ]
