# Generated by Django 2.2.7 on 2020-01-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20191220_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='published'),
        ),
    ]
