# Generated by Django 2.2.7 on 2020-01-15 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20200113_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'default_related_name': 'articles', 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='article',
            new_name='articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='articles', to='posts.Category'),
        ),
    ]
