# Generated by Django 2.2.7 on 2020-01-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20200120_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='archived',
        ),
    ]
