# Generated by Django 3.0.3 on 2020-02-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20200220_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='id',
            new_name='uid',
        ),
    ]
