# Generated by Django 3.0.3 on 2020-03-11 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20200311_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/articles', verbose_name='cover')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['-created'],
                'default_related_name': 'images',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
