# Generated by Django 3.0.3 on 2020-03-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20200311_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ForeignKey(db_column='article', default='43229962-b0e1-46ed-917b-b4e31e47dba1', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.Article'),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(default='test', verbose_name='slug'),
        ),
    ]
