# Generated by Django 3.0.3 on 2020-03-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20200311_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='article',
            field=models.ForeignKey(db_column='article', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.Article'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
