# Generated by Django 3.0.3 on 2020-03-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0039_auto_20200312_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to='images/articles', verbose_name='image'),
        ),
    ]
