# Generated by Django 3.0.3 on 2020-03-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_auto_20200312_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
