# Generated by Django 3.0.4 on 2020-04-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0042_auto_20200312_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
