# Generated by Django 3.0.4 on 2020-04-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0045_auto_20200404_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=303, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
