# Generated by Django 3.0.4 on 2020-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0046_auto_20200404_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=25, unique=True, verbose_name='slug'),
        ),
    ]
