# Generated by Django 3.0.4 on 2020-04-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0047_auto_20200404_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'default_related_name': 'articles', 'get_latest_by': ['-created'], 'ordering': ['-published', 'title'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'categories', 'get_latest_by': ['-created'], 'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments', 'get_latest_by': ['-created'], 'ordering': ['name'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'default_related_name': 'images', 'get_latest_by': ['-created'], 'ordering': ['article'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'get_latest_by': ['-created'], 'ordering': ['name'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, max_length=303, null=True, unique=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='posts.Tag'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='images/articles', verbose_name='image'),
        ),
    ]
