# Generated by Django 3.0.4 on 2020-04-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0049_auto_20200404_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='reviewed'),
        ),
    ]
