# Generated by Django 3.0.4 on 2020-04-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0051_auto_20200429_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
    ]
