# Generated by Django 3.0.4 on 2020-04-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0054_auto_20200430_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='archived',
        ),
    ]
