# Generated by Django 3.0.4 on 2020-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0055_remove_article_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='month',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='year'),
        ),
    ]
