# Generated by Django 3.0.4 on 2020-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0056_auto_20200430_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(max_length=303, unique=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(unique=True, verbose_name='body'),
        ),
    ]
