# Generated by Django 3.0.4 on 2020-04-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0062_auto_20200430_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
    ]
