# Generated by Django 3.0.4 on 2020-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0064_auto_20200430_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='month',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='month'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='year'),
        ),
    ]
