# Generated by Django 2.2.7 on 2019-11-28 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('message', models.TextField(verbose_name='message')),
                ('reply', models.BooleanField(default=False, verbose_name='reply')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
