# Generated by Django 3.0.3 on 2020-03-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20200227_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='terms',
            field=models.BooleanField(default=False, verbose_name='terms'),
        ),
    ]
