# Generated by Django 3.0.4 on 2020-03-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_message_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='name'),
        ),
    ]
