# Generated by Django 2.2.7 on 2019-11-28 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('terms', models.BooleanField(default=False, verbose_name='terms and conditions')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='subscribed')),
            ],
            options={
                'verbose_name': 'subscriber',
                'verbose_name_plural': 'subscribers',
            },
        ),
    ]
