# Generated by Django 3.0.3 on 2020-02-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20200220_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'default_related_name': 'subscribers', 'ordering': ['-updated'], 'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.CharField(max_length=50, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
    ]
