# Generated by Django 3.0.3 on 2020-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_auto_20200227_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.BooleanField(default=True, verbose_name='subscribed'),
        ),
    ]
