# Generated by Django 3.0.4 on 2020-04-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20200311_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='name'),
        ),
    ]
