# Generated by Django 3.0.4 on 2020-04-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20200404_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'default_related_name': 'subscribers', 'get_latest_by': ['-created'], 'ordering': ['-updated'], 'verbose_name': 'subscriber', 'verbose_name_plural': 'subscribers'},
        ),
    ]
